import os
import sys
import struct
import shutil

def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_icon_assets.py <path_to_generated_png>")
        sys.exit(1)
        
    src_png = sys.argv[1]
    dest_dir = os.path.dirname(os.path.abspath(__file__))
    dest_png = os.path.join(dest_dir, "app_icon.png")
    dest_ico = os.path.join(dest_dir, "app_icon.ico")
    dest_hpp = os.path.join(os.path.dirname(dest_dir), "src", "ui", "app_icon.hpp")
    
    print(f"Source PNG: {src_png}")
    print(f"Destination PNG: {dest_png}")
    print(f"Destination ICO: {dest_ico}")
    print(f"Destination HPP: {dest_hpp}")
    
    # 1. Copy PNG
    shutil.copy2(src_png, dest_png)
    print("Copied PNG to resources directory.")
    
    # Ensure PIL (Pillow) is installed
    try:
        from PIL import Image
    except ImportError:
        print("Pillow not found, attempting to install it via pip...")
        import subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow"])
        from PIL import Image
        
    # 2. Save ICO (Multi-resolution)
    img = Image.open(dest_png)
    sizes = [(256, 256), (128, 128), (64, 64), (48, 48), (32, 32), (16, 16)]
    img.save(dest_ico, format="ICO", sizes=sizes)
    print(f"Successfully generated multi-resolution ICO at: {dest_ico}")
    
    # 3. Save C++ Header for GLFW window icon
    # We will generate a header with two sizes: 48x48 and 32x32
    hpp_content = []
    hpp_content.append("// Automatically generated by generate_icon_assets.py. Do not edit.")
    hpp_content.append("#pragma once")
    hpp_content.append("")
    hpp_content.append("namespace forge {")
    hpp_content.append("")
    
    for size in [48, 32, 16]:
        resized_img = img.resize((size, size), Image.Resampling.LANCZOS)
        # Convert to RGBA
        rgba_img = resized_img.convert("RGBA")
        pixels = list(rgba_img.getdata())
        
        # Format as C++ array
        hpp_content.append(f"// Raw RGBA pixels for {size}x{size} icon")
        hpp_content.append(f"inline const int app_icon_{size}_width = {size};")
        hpp_content.append(f"inline const int app_icon_{size}_height = {size};")
        hpp_content.append(f"inline const unsigned char app_icon_{size}_rgba[] = {{")
        
        # Chunk pixel bytes to keep lines manageable
        byte_list = []
        for p in pixels:
            # p is (R, G, B, A)
            byte_list.extend([f"0x{p[0]:02X}", f"0x{p[1]:02X}", f"0x{p[2]:02X}", f"0x{p[3]:02X}"])
            
        # Write bytes in chunks of 16
        for i in range(0, len(byte_list), 16):
            chunk = byte_list[i:i+16]
            hpp_content.append("    " + ", ".join(chunk) + ",")
            
        hpp_content.append("};")
        hpp_content.append("")
        
    hpp_content.append("} // namespace forge")
    
    # Ensure directory exists for HPP
    os.makedirs(os.path.dirname(dest_hpp), exist_ok=True)
    with open(dest_hpp, "w") as f:
        f.write("\n".join(hpp_content))
        
    print(f"Successfully generated C++ header at: {dest_hpp}")

if __name__ == "__main__":
    main()
